ns: &DEFAULT

  #General
  # For computing compression
  n_params_baseline: None #If None, will be computed
  verbose: True
  arch: 'fno'

  #Distributed computing
  distributed:
    use_distributed: False
    wireup_info: 'mpi'
    wireup_store: 'tcp'
    model_parallel_size: 2
    seed: 666

  # Model hyperparameters
  fno:
    data_channels: 1
    in_channels: 1
    out_channels: 1
    n_modes: [64, 64]
    hidden_channels: 62
    lifting_channel_ratio: 4.13
    projection_channel_ratio: 4.13
    n_layers: 4
    domain_padding: 0.0
    domain_padding_mode: 'one-sided' # OR 'symmetric'
    norm: None
    use_channel_mlp: True
    channel_mlp_skip: 'soft-gating'
    implementation: 'reconstructed'
    positional_embedding: 'grid'
    
    channel_mlp_expansion: 0.5
    channel_mlp_dropout: 0

    separable: False
    factorization: None
    rank: 1.0
    fixed_rank_modes: None
    fno_block_precision: 'full' # or 'half', 'mixed'
    stabilizer: None # or 'tanh'

  # Optimizer
  opt:
    n_epochs: 500
    learning_rate: 5e-4
    weight_decay: 1e-4
    amp_autocast: False
    callbacks: None

    scheduler_T_max: 500 # For cosine only, typically take n_epochs
    scheduler_patience: 5 # For ReduceLROnPlateau only
    scheduler: 'StepLR' # Or 'CosineAnnealingLR' OR 'ReduceLROnPlateau'
    step_size: 33
    gamma: 0.5

  # Data
  data:
    folder: /home/miguel/data/navier_stokes
    batch_size: 16
    n_train: 10000
    train_resolution: 128
    n_tests: [2000, 2000, 1000, 1000, 1000]
    test_resolutions: [64, 128, 256, 512, 1024] 
    test_batch_sizes: [32, 16, 8, 4, 1]

    encode_input: True
    encode_output: False
    num_workers: 0
    pin_memory: False
    persistent_workers: False

  # Weights and biases
  wandb:
    log: False
    name: None # If None, config will be used but you can override it here
    group: '' 
    project: ""
    entity: "" # put your username here
    sweep: False
    log_output: False
    log_test_interval: 1