ns: &DEFAULT

  #General
  # For computing compression
  n_params_baseline: None
  verbose: True
  arch: 'oformer'

  #Distributed computing
  distributed:
    use_distributed: False
    wireup_info: 'mpi'
    wireup_store: 'tcp'
    model_parallel_size: 2
    seed: 666

  # OFormer
  oformer:
    data_channels: 1
    n_dim: 2
    in_channels: 1
    out_channels: 1
    encoder_hidden_channels: 220
    decoder_hidden_channels: 280
    encoder_num_heads: 16
    decoder_num_heads: 32
    encoder_n_layers: 4
    norm: 'layer_norm'
    query_basis: 'siren'

    use_decoder: False

    # Should only be true for equidistant grids
    spectral_conv_encoder: True
    num_modes: 16

  # Optimizer
  opt:
    n_epochs: 201
    learning_rate: 1e-4 # for cosine annealing, this is the max learning rate
    weight_decay: 1e-6
    amp_autocast: False
    callbacks: None

    scheduler_T_max: 500 # For cosine only, typically take n_epochs
    scheduler_patience: 5 # For ReduceLROnPlateau only
    max_lr: 5e-3 # For OneCycleLR only
    scheduler_eta_min: 1e-7
    scheduler: 'StepLR' #'StepLR' OR 'CosineAnnealingLR' OR 'ReduceLROnPlateau' OR 'OneCycleLR'
    step_size: 33
    gamma: 0.5

  # Data
  data:
    folder: /home/miguel/data/navier_stokes
    batch_size: 2
    n_train: 10000
    train_resolution: 128
    n_tests: [2000] #, 2000, 1000, 1000, 1000]
    test_resolutions: [128] #[64, 128, 256, 512, 1024] 
    test_batch_sizes: [12] #[24, 12, 6, 3, 1]

    encode_input: True
    encode_output: False
    num_workers: 0
    pin_memory: False
    persistent_workers: False

  # Weights and biases
  wandb:
    log: False
    name: None # If None, config will be used but you can override it here
    group: '' 
    project: ""
    entity: "" # put your username here
    sweep: False
    log_output: False
    log_test_interval: 1